# Generated by Django 6.0.3 on 2026-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("lost", "Lost"),
                ],
                default="lead",
                max_length=10,
            ),
        ),
    ]
