# Generated by Django 6.0.3 on 2026-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="clients",
            new_name="client",
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("call", "Call"),
                    ("email", "Email"),
                    ("meeting", "Meeting"),
                    ("video", "Video call"),
                    ("note", "Note"),
                ],
                max_length=20,
            ),
        ),
    ]
