# Generated by Django 6.0.3 on 2026-05-02 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_clientnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientnote",
            name="created_by",
        ),
        migrations.AddField(
            model_name="clientnote",
            name="tags",
            field=models.ManyToManyField(blank=True, to="clients.tag"),
        ),
        migrations.AddField(
            model_name="clientnote",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_notes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
