# Generated by Django 6.0.3 on 2026-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_usersettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="last_notification_check",
        ),
        migrations.AddField(
            model_name="user",
            name="last_notification_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
