# Generated by Django 6.0.3 on 2026-07-03 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_usersettings_last_notification_check_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_notification_check",
        ),
    ]
